### ISSUE TITLE
Hotels: sending invalid query for arabic languages

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/mobile#734] opened 2018-06-12 07:18 UTC
Operation:

```graphql
query AllHotelsSearchQuery($after: String, $filter: HotelsFilterInput!, $first: Int, $options: AvailableHotelOptionsInput, $search: HotelsSearchInput!) {
  ...AllHotelsSearchList_data
}
fragment AllHotelsSearchList_data on RootQuery {
  allAvailableHotels(after: $after, filter: $filter, first: $first, options: $options, search: $search) {
    edges {
      cursor
      node {
        __typename
        id
        ...AllHotelsSearchRow
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    stats {
      priceMax
      priceMin
    }
  }
}
fragment AllHotelsSearchRow on HotelAvailability {
  hotel {
    id
    mainPhoto {
      id
      lowResUrl
    }
    ...HotelReviewScore_hotel
  }
  ...HotelTitle
}
fragment HotelDistance_hotel on Hotel {
  distanceFromCenter
}
fragment HotelReviewScore_hotel on Hotel {
  review {
    score
  }
}
fragment HotelTitle on HotelAvailability {
  hotel {
    id
    name
    rating {
      stars
    }
    ...HotelDistance_hotel
  }
  price {
    amount
    currency
  }
}
```

Query variables:

```json
{
    "filter": "{\"freeCancellation\":false,\"hotelFacilities\":null,\"maxPrice\":null,\"minPrice\":null,\"minScore\":null,\"starsRating\":[]}",
    "options": "{\"currency\":\"SAR\"}",
    "first": "50",
    "after": "",
    "search": "{\"checkin\":\"٢٠١٨-٠٧-٠٣\",\"checkout\":\"٢٠١٨-٠٧-٠٤\",\"cityId\":\"aG90ZWxDaXR5Oi0yNjc5NjUy\",\"roomsConfiguration\":{\"adultsCount\":1,\"children\":[]}}"
}
```

<img width="1074" alt="screen shot 2018-06-12 at 09 17 55" src="https://user-images.githubusercontent.com/978368/41275550-8855f350-6e21-11e8-9d30-c77114ada0d9.png">
<img width="436" alt="screen shot 2018-06-12 at 09 17 47" src="https://user-images.githubusercontent.com/978368/41275551-887d88d4-6e21-11e8-86fe-055c60ac45af.png">

**Comment by mrtnzlml** [comment] 2018-06-12 07:20
Note: I do not know how to reproduce it. _(maybe again problem only with production build?)_

**Comment by lukewalczak** [comment] 2018-06-28 09:38
I'm also unable to reproduce it. After an investigation, I've noticed that `checkin` and `checkout`dates are displayed in the Arabic language, but they are sent properly as `2018-07-05`.

**Comment by tbergq** [comment] 2018-08-10 07:32
@pistelak will look into it. 

Please update us here on the progress @pistelak 🙂

**Comment by pistelak** [comment] 2018-08-10 13:51
@tbergq Should be fixed in Monday's release.

**Comment by tbergq** [comment] 2018-08-10 13:53
@pistelak thank you

**Closed by tbergq** 2018-08-10 13:53 UTC
Labels: bug, callstack
